name: deploy

# 代码提交到master分支时触发github action
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: 检查
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: 安装 Hugo
          uses: peaceiris/actions-hugo@v3
          with:
              hugo-version: "latest"
              extended: true

        - name: 构建页面
          run: hugo -D

        - name: 部署页面
          uses: peaceiris/actions-gh-pages@v4
          with:
              PERSONAL_TOKEN: ${{ secrets.TOKEN }}
              EXTERNAL_REPOSITORY: ColaBlack/ColaBlack.github.io
              PUBLISH_BRANCH: master
              PUBLISH_DIR: ./public
              commit_message: 自动部署
